branches:
  only:
  - pelican
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make publish
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
  - secure: pssMEN6gYwYD+TMYA3PbWvaKHQVW38UVBvSd8S8sVg7wMNTZwXmdRQ2+sb3N/Dezr5f4LQSAPUXThMoTGPAW/hW7QiVApxeiYpy7sHgM3KaYilczk/Bl8Vew3vCMLjfjlKeOTOP9HwBfOdkU3/dfI5VazoNklt9kykHWeiC00Po3XTMVBti/LtErwGgPW7mD+UZATqqqJtOxddut7FvyOMs4bY7Hjb4qHzz18+aGtJZVf9EkslBA+tm1lWiHg7VyWwvArGDeUHbgwd3qMCOqNJy5GcM5hGv090OZ6SVEJGC50q6RAemqvHb0la77oUqIvOR3OgXoiHrbQ7g+dU8rY1Uh4t6LnZA/1TqbGVzqPdtX62EgadocXbaznekrDBKLyQCoTfmNSmmw6+II5snEux3e0YL2ruquIP0zjg0SaTLgz13JlRx5QEjnYpwhNha8VVQ7b4sW3bK/yg0/bcz3B0zhd2kNVcDAdrbOM2H7ffetbo6zTSXONrZnv8q/muT5om4QVTSM30oFlkIlPkjI0FgPo5N0Fg3wOyj9qIzAU67cD4wLyy3/ZCmEy7INHTFpyv0Zt8i9JMABE+pnda9NJxiHNg/R2mGemHf+NqQvJsb29FwKkvz7JhxCmyxuxODRhNBNtdpRF2RNRQaT/eukopjNpeB+l1onnNFXQaPGORs=
before_install:
- git submodule update --remote --merge
after_success: bash deploy.sh
